#!/bin/bash -eu
#
# Temporary(?) hacks
#

# shellcheck disable=SC2153
for cmdline_txt in ${CMDLINE_TXT}; do
	if ! grep -q 'net.ifnames=0' "${cmdline_txt}" ; then
		echo "-- Disable persistent net names"
		sed -i 's/^/net.ifnames=0 /' "${cmdline_txt}"
	fi
done
