#!/bin/bash -eu
#
# Set cloud-init config
#

if [ -e "${BOOT_DIR}"/user-data ] ; then
	echo "-- Clear cloud-init user-data"
	# Purge cloud-init cruft
	cat << EOF > "${BOOT_DIR}"/user-data
#cloud-config
EOF
fi

if [ -e "${ROOT_DIR}"/etc/cloud/cloud.cfg ] ; then
	echo "-- Disable users-groups in cloud.cfg"
	sed -i 's/\(^\s*-\s*users[_-]groups\)/# rpi-install \1/' \
	    "${ROOT_DIR}"/etc/cloud/cloud.cfg
fi
