#!/bin/bash -eu
#
# Set raspberrypi config
#

echo "-- Set config (${*})"

# shellcheck disable=SC2153
for config_txt in ${CONFIG_TXT} ; do
	{
		echo
		for opt in "${@}" ; do
			echo "${opt}"
		done
	} >> "${config_txt}"

	echo "   ${config_txt}"
done
